// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztltcrxgjlvtywrlemrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bHRjcnhnamx2dHl3cmxlbXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjU1NDgsImV4cCI6MjA3MDAwMTU0OH0.O61j8slEReWu145uudpBzPPONXdCnL02MkOD0pGNvLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});